analyzer_rules:
  - explicit_self

included:
  - Searchy

excluded:
  - SearchyTests
  - SearchyUITests

allow_zero_lintable_files: false

type_name:
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode"
